[package]
name = "forest-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
threading = []
default = []

[dependencies]
num-traits = "0.2.16"
subtle = "2.5.0"

[lib]
crate-type = ["cdylib", "rlib"]