[package]
name = "arborist-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
threading = []
simd = []
no_std = ["bumpalo"]
default = []

[dependencies]
arborist-proc = {version = "0.1.0", path = "../proc"}
bumpalo = { version = "3.13.0", optional = true }
quote = "1.0.33"

[lib]
crate-type = ["cdylib", "rlib"]