[package]
name = "arborist-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
threading = []
default = []

[dependencies]
arborist-proc = {version = "0.1.0", path = "../proc"}

[lib]
crate-type = ["cdylib", "rlib"]